# Generated by Django 3.2.9 on 2021-12-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_orderitem_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address_landmark',
            new_name='address_landmark',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Address_pincode',
            new_name='address_pincode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Address_street',
            new_name='address_street',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
